packages:
  - name: botocore
    path: ./botocore-stubs
    checks:
      flake8: false
      pyright: false
      mypy: false
      stubtest:
        enabled: true
        command: python -m mypy.stubtest --ignore-disjoint-bases
    snapshots:
      stubtest: |-
        error: botocore.vendored failed to find stubs
        Stub:
        MISSING
        Runtime:
        <module 'botocore.vendored' from './botocore/vendored/__init__.py'>

        error: botocore.vendored.requests failed to find stubs
        Stub:
        MISSING
        Runtime:
        <module 'botocore.vendored.requests' from './botocore/vendored/requests/__init__.py'>

        error: botocore.vendored.requests.exceptions failed to find stubs
        Stub:
        MISSING
        Runtime:
        <module 'botocore.vendored.requests.exceptions' from './botocore/vendored/requests/exceptions.py'>

        error: botocore.vendored.requests.packages failed to find stubs
        Stub:
        MISSING
        Runtime:
        <module 'botocore.vendored.requests.packages' from './botocore/vendored/requests/packages/__init__.py'>

        error: botocore.vendored.requests.packages.urllib3 failed to find stubs
        Stub:
        MISSING
        Runtime:
        <module 'botocore.vendored.requests.packages.urllib3' from './botocore/vendored/requests/packages/urllib3/__init__.py'>

        error: botocore.vendored.requests.packages.urllib3.exceptions failed to find stubs
        Stub:
        MISSING
        Runtime:
        <module 'botocore.vendored.requests.packages.urllib3.exceptions' from './botocore/vendored/requests/packages/urllib3/exceptions.py'>

        error: botocore.vendored.six failed to find stubs
        Stub:
        MISSING
        Runtime:
        <module 'botocore.vendored.six' from './botocore/vendored/six.py'>
